export const templateEmail = {
    WELCOME_TEMPLATE: 1,
    RESET_PASSWORD_TEMPLATE: 2,
    INVITATION_TEMPLATE: 3,
    RETRY_INVITATION_TEMPLATE: 4,
    NEW_MESSAGE_TEMPLATE: 5,
    NEW_DOCUMENT_TEMPLATE: 6,
};